id: pkgupd
version: 2200
about: rlxos package manager
depends:
  runtime:
    - libyaml-cpp
  buildtime:
    - cmake
type: app
bundle: true
build-dir: pkgupd-main

sources:
  - pkgupd-2200.tar.gz::https://github.com/itsManjeet/pkgupd/archive/refs/heads/main.tar.gz

pre-script: |
  mkdir -p ${pkgupd_pkgdir}/usr/lib

post-script: |
  install -v -D -m 0644 assets/pkgupd.png ${pkgupd_pkgdir}/pkgupd.png
files:
  - path: AppRun
    perm: 0755
    content: |
      #!/bin/sh
      SELF=$(readlink -f "$0")
      HERE=${SELF%/*}
      export LD_LIBRARY_PATH=${HERE}/usr/lib:${LD_LIBRARY_PATH}
      exec ${HERE}/usr/bin/pkgupd $@
  - path: pkgupd.desktop
    content: |
      [Desktop Entry]
      Name=pkgupd
      Type=Application
      Version=1.0
      Comment=A Universal Package Manager URI Handler
      Exec=pkgupd %u
      Icon=pkgupd
      MimeType=x-scheme-handler/pkgupd;
      Categories=System;