id: test-package
version: 0.1.0
about: Sample recipe file

type: pkg

sources:
  - https://web.url/to/package

depends:
  runtime:
    - pkg1
    - pkg2
  buildtime:
    - pkg3
    - pkg4

environ:
  - ENV=1


prescript: |
  execute pre build script

postscript: |
  execute post script

script: |
  execute script

build-type: cmake

build-dir: acl-{{version}}

configure: >
  --disable-static

split:
  - into: lib
    about: test-package library
    files:
      - /usr/lib/libtest.so