#!/bin/bash

APPIMAGE_PATH="${1}"
if [[ -z ${APPIMAGE_PATH} ]] ; then
    echo "no app file specified"
    exit 1
fi

zenity --question \
    --title='Uninstall' \
    --text="Do you want to remove $(basename ${APPIMAGE_PATH} | sed '#s.app##')" && {
    if [[ -e ${APPIMAGE_PATH} ]] ; then
        rm ${APPIMAGE_PATH}
    fi
}